### ISSUE TITLE
DB모델링

### ISSUE THREAD

**Issue by 2sg** [f-lab-edu/kream#24]
프로젝트 kream에 필요한 DB테이블들을 설계하고 ERD로 작성합니다

**Comment by 2sg** [comment]
@f-lab-robert 작성진행중인 erd공유드립니다 https://www.erdcloud.com/d/T6NCBjnTfyLngxisK

**Comment by f-lab-robert** [comment]
![image-01](https://user-images.githubusercontent.com/84081620/159124032-5631a5e4-7dc2-45c3-863b-1703d991ae80.jpeg)
![image-02](https://user-images.githubusercontent.com/84081620/159124034-e599351c-7f82-43ee-b6b1-1089da10a88a.jpeg)

**Comment by f-lab-robert** [comment]
![image-01](https://user-images.githubusercontent.com/84081620/159124077-71abd199-23fe-495c-be23-5f7b49c3b0be.jpeg)
![image-02](https://user-images.githubusercontent.com/84081620/159124079-6133ee7d-1608-4024-9906-6c5b0453de6a.jpeg)

**Comment by f-lab-robert** [comment]
시간이 되실 때 DB 정규화와 관계 표기법 등에 대해서도 학습해보시면 좋을 것 같습니다.

**Comment by 2sg** [comment]
https://www.erdcloud.com/d/T6NCBjnTfyLngxisK 말씀해주신 내용들 반영하여 erd작성하였습니다

**Comment by f-lab-robert** [comment]
ㄹㄴㅇㄹㄴㅇㄹㄴㅇㄹㄴㅇㄹㄴㅇㄹ문제가 있다.... 망했다...

**Comment by 2sg** [comment]
https://www.erdcloud.com/d/T6NCBjnTfyLngxisK 
변경된 erd공유합니다
